#!/bin/bash

# Fish
ln -f -s ~/src/osx/osxscripts.git/functions ~/.config/fish
ln -f -s ~/src/osx/osxscripts.git/config.fish ~/.config/fish/config.fish

# Vim
ln -f -s ~/src/osx/osxscripts.git/.vim ~/.vim
ln -f -s ~/src/osx/osxscripts.git/vimrc ~/.vimrc
ln -f -s ~/src/osx/osxscripts.git/gvimrc ~/.gvimrc
ln -f -s ~/src/osx/osxscripts.git/tim.vim ~/tim.vim
ln -f -s ~/src/osx/osxscripts.git/tim.settings.vim ~/tim.settings.vim
ln -f -s ~/src/osx/osxscripts.git/tim.utils.vim ~/tim.utils.vim

# Bash
ln -f -s ~/src/osx/osxscripts.git/.bash_profile ~/.bash_profile

# ZSH
ln -f -s ~/src/osx/osxscripts.git/.zshrc ~/.zshrc
