#!/bin/bash

mkdir ~/.config
mkdir ~/.config/nvim

# Fish
# ln -f -s ~/src/osx/osxscripts.git/functions ~/.config/fish
# ln -f -s ~/src/osx/osxscripts.git/config.fish ~/.config/fish/config.fish

# Vim
ln -f -s ~/src/osx/osxscripts.git/.vim ~/.vim
ln -f -s ~/src/osx/osxscripts.git/.vim ~/.nvim
ln -f -s ~/src/osx/osxscripts.git/vimrc ~/.vimrc
ln -f -s ~/src/osx/osxscripts.git/gvimrc ~/.gvimrc
ln -f -s ~/src/osx/osxscripts.git/gvimrc ~/.config/nvim/init.vim
ln -f -s ~/src/osx/osxscripts.git/tim.vim ~/tim.vim
ln -f -s ~/src/osx/osxscripts.git/tim.settings.vim ~/tim.settings.vim
ln -f -s ~/src/osx/osxscripts.git/tim.utils.vim ~/tim.utils.vim
ln -f -s ~/src/osx/osxscripts.git/.gitconfig ~/.gitconfig
ln -f -s ~/src/osx/osxscripts.git/.xvimrc ~/.xvimrc

# Bash
ln -f -s ~/src/osx/osxscripts.git/.bash_profile ~/.bash_profile

# ZSH
ln -f -s ~/src/osx/osxscripts.git/.zshrc ~/.zshrc
mkdir ~/.oh-my-zsh/custom/themes
ln -f -s ~/src/osx/osxscripts.git/zsh-themes/bullet-train.zsh-theme ~/.oh-my-zsh/custom/themes/bullet-train.zsh-theme
ln -f -s ~/src/osx/osxscripts.git/zsh-themes/powerline.zsh-theme ~/.oh-my-zsh/custom/themes/powerline.zsh-theme

# SSH
mkdir ~/.ssh
ln -f -s ~/src/osx/osxscripts.git/.ssh/config ~/.ssh

# Alacritty
mkdir ~/.config/alacritty
ln -f -s ~/.config/alacritty/alacritty.yml
