#!/bin/bash

# Fish
ln -s ~/Documents/src/osx/osxscripts.git/functions ~/.config/fish
ln -s ~/Documents/src/osx/osxscripts.git/config.fish ~/.config/fish/config.fish

# Vim
ln -s ~/Documents/src/osx/osxscripts.git/.vim ~/.vim
ln -s ~/Documents/src/osx/osxscripts.git/vimrc ~/.vimrc
ln -s ~/Documents/src/osx/osxscripts.git/gvimrc ~/.gvimrc
ln -s ~/Documents/src/osx/osxscripts.git/tim.vim ~/tim.vim
ln -s ~/Documents/src/osx/osxscripts.git/tim.settings.vim ~/tim.settings.vim
ln -s ~/Documents/src/osx/osxscripts.git/tim.utils.vim ~/tim.utils.vim

# Bash
ln -s ~/Documents/src/osx/osxscripts.git/.bash_profile ~/.bash_profile
